### ISSUE TITLE
build시 확장 프로그램으로 추가하지 않고 main함수로 실행할수 있는 방법이 있는지 궁금합니다. 

### ISSUE THREAD

**Issue by supersolaris** [ebandal/H2Orestart#13]
안녕하세요. 소중한 시간을 내셔셔 개발하신 소스 잘보고 있습니다.
다름이 아니라 해당 소스를 이용해서 몇가지 수정해볼려고 하는데 
할때마다 플러그인 추가해야 해서 main함수로 바로 실행할수 있으면
좀 더 수월하게 수정할수 있을듯해서 문의차 이슈에 몇자 적습니다. 
그럼 멋진 하루 되시기 바랍니다.

**Comment by ebandal** [comment]
안녕하세요. 
main 메소드를 포함한 소스 첨부합니다.
LibreOiffce library를 추가해야 합니다만,  이미 빌드하실 수 있는 환경인듯 하니  약간 수정만 하시면 사용하실 수 있을듯 하네요.
[Hwp2Swriter.zip](https://github.com/ebandal/H2Orestart/files/12409396/Hwp2Swriter.zip)

**Comment by ebandal** [comment]
샘플코드 제공했습니다. 이슈 닫습니다.
