### ISSUE TITLE
Error  connected file with Network(samba)

### ISSUE THREAD

**Issue by queenmedley** [ebandal/H2Orestart#14]
It works well on Arch Linux, LibreOffice 7.6.2.1. thanks.
However, when opening a file on a network connected via samba, "a corrupted file error" occurs.
I don't know if it's a problem with this extension or LibreOffice. However, there is no problem opening other types of files, but only hwp files cannot be opened on a network conneted.

**Comment by ebandal** [comment]
Thanks for reporting issue, but I can't tell what cause the problem.
I copied hwp file to my network drive (SMBv2) and I tried to reproduce your symptom. but I  couldn't.  Hwp file was opened normally in LibreOffice. 

Could you provide some more information for further analysis? 
Such as "ls -al" result for that file,  screen shot of error message or  log file archive.
log files are located in   ~/.H2Orestart/

**Comment by queenmedley** [comment]
I found out that this error occurs when opening a file by double-clicking in the Nautilus file manager.

import_0.log message is
[11-23 10:00] (riterContext.dete) INFO: file detected not HWPX
[11-23 10:00] (riterContext.dete) INFO: file detected neither HWPX nor HWP
[11-23 10:00] (OrestartImpl.dete) INFO: File is not Hancomm document.

![스크린샷 2023-11-23 10-00-17](https://github.com/ebandal/H2Orestart/assets/16573046/c49de6bb-a91b-4de2-9a61-5e526486224d)

I tried another method.
I ran LibreOffice and opened the network file through 
Then I was able to open it as read-only.

The strange thing is that when I open a file using LibreOffice's remote open, the same error occurs as when I double-clicked it in Nautilus.

note for my smb.conf  protocol is set
  client min protocol = NT1
  client max protocol = SMB3

**Comment by ebandal** [comment]
I modified extension to support network URL type.
I tested some smb URL cases in Linux, but not much cases.  because my main environment is MS Windows.  ftp URL cases can be tested on Windows LibreOffice, but smb URL cases cannot.
I'm pretty assure modification works almost same on smb and ftp cases.
Modification is included in v0.5.8. I hope this release resolve your issue.

**Comment by queenmedley** [comment]
I tested it on version 5.8, but the same error still occurs when opening a file on the linux network.
It was confirmed that it works well in a Windows environment. 
Once again, I feel that Linux is difficult to set up a network for beginners.
For the time being, I will be copying and working locally. Thank you for the quick response

**Comment by ebandal** [comment]
I have no idea why issue still ocuurs. 
I will keep looking into this issue until resolved.
Thank you.

**Comment by queenmedley** [comment]
어제 다른분이 된다는 메일을 받고 혹시하고 테스트를 해보다 원인을 일부 확인했습니다.

네트워크 파일에 접근할때  마운트 명령어를 사용해서 마운트를 하면 노틸러스 같은 파일 탐색기에서 더블클릭을 하든 열기를 하든
하면 잘 열리네요..
-----------------------------------------------------------------------------
sudo  mount -t cifs //zzen/home /mnt/sss  
-----------------------------------------------------------------------------

그러나 그놈의 노틸러스같은 파일관리자의 주소창으로 열게되면 위와 같은 에러가 발생합니다.
노틸러스 같은 파일관리자에서 네트워크에 연결하는 방식이 일반 mount 명령어 방식이 아니고
gvfs-smb 인걸로 알고 있는데 연결 방식이 다른거 같습니다.
---------------------------------------------------------------------------
smb://zzen/home 
-----------------------------------------------------------------------

암튼 gvfs-smb 에서 문제가 발생하는 해결하는데 도움이 되었음합니다.

**Comment by ebandal** [comment]
해결된 것으로 이해하고  close하겠습니다.
