### ISSUE TITLE
특정 한글 hwpx 파일 변환 및 열기 시, 즉시 종료되는 현상

### ISSUE THREAD

**Issue by polestar6353** [ebandal/H2Orestart#16]
안녕하십니까. 좋은 확장프로그램을 만들어주셔서 늘 감사하게 사용하고 있습니다.

일반적으로 다른 hwp, hwpx는 정상적으로 변환되거나, 열리지만, 문서 내 특정 타입의 요소가 존재하는 경우에는 하기 이슈들이 발생 하고 있습니다. 해당 요소를 삽입한 문서를 본 이슈 최 하단에 첨부하겠습니다.

다음과 같은 이슈가 발생합니다.

1. cli에서 soffice --convert-to 명령어 동작 시, Unspecified Application Error 가 발생.
환경은 다음과 같습니다.
- Ubuntu 22.04
- LibreOffice 7.3.7.2
- H2Orestart 0.5.8

2. window 환경에서 libreOffice 에서 동일한 파일을 열 경우, libreOffice 자체가 종료되는 현상
환경은 다음과 같습니다.
- window 11 22H2
- LibreOffice 7.6.4.1
- H2Orestart 0.5.8

아마 동일한 사유일것으로 판단됩니다만, 해당 이슈에 대해 확인 해 주실 수 있으시다면 확인 요청드리겠습니다.

좋은 확장 프로그램을 만들어 주셔서 다시한번 감사드립니다.

---

hwpx가 첨부되지 않아 압축하여 첨부드립니다.

[notConverted.zip](https://github.com/ebandal/H2Orestart/files/13659616/notConverted.zip)

**Comment by ebandal** [comment]
버그 리포트 감사합니다. 
이슈 내용 확인했고,   이번주 내로 수정하여   차주에  수정버전 배포할 예정입니다.

**Comment by ebandal** [comment]
HWPX 에서 수식(equation)을 잘못 읽어오는 문제가 있었습니다.  
수식값이 null 이 되어  NullPointerException 발생하는 이슈입니다.
수정하여  v0.5.9 릴리스하겠습니다.

**Comment by polestar6353** [comment]
정상적으로 열리는 부분 확인완료되었습니다.
확인 및 수정 감사드립니다

**Comment by polestar6353** [comment]
안녕하십니까, v.0.5.9 의 경우 수식과 관련된 문제가 수정되었음을 확인했습니다. 정말 감사드립니다.

다만, 여전히 열리지 않는 파일의 케이스를 두 종류 찾았습니다.
외부의 hwp 파일인 만큼, 파일이 열리지 않도록 하는 부분을 제외하고는 전부 제거한 뒤, 파일을 업로드 드립니다.

총 파일은 두 개 입니다.

실행 환경은 위와 같으며, H2ORestart 만 v.0.5.9 가 되었습니다.

저번의 수식 기능처럼 눈에 보이는 기능이 아니라서, 정확히 어떤 기능의 문제인지조차 파악하기가 어렵습니다.
아마 용지나 문서 전반의 스타일과 관련된 이슈일 수 있습니다.

두 파일의 이슈가 같을수도 있고 다를수도 있습니다. 저는 로그를 확인할 수 없다보니, 해당 부분마저도 제대로 파악하기 어려운 문제가 있습니다.

좋은 확장 프로그램을 만들어 주셔서 

늘 감사드립니다.

[notOpenIssue.zip](https://github.com/ebandal/H2Orestart/files/13972122/notOpenIssue.zip)

**Comment by ebandal** [comment]
안녕하세요. 
두 파일 열리지 않고 crash 발생하는 원인은 한가지로 동일합니다.
머리말/꼬리말 적용 범위를 읽지 못하는 오류가 있었습니다.
NULL이 되는게 오류여서 NULL값이 안되도록 하는 게 해결책이지만,  사실 제대로 처리하는 방법을 모릅니다.
한컴 파일형식문서에는 머리말/꼬리말 부분을 14bytes 읽도록 되어 있으나,  실제 한컴문서는 머리말/꼬리말 정보가 8bytes 뿐입니다.
어쨋든 NULL 오류가 발생하지 않도록  수정해서  조만간 배포하겠습니다.

**Comment by ebandal** [comment]
수정사항 반영하여 v0.5.10 배포합니다. 감사합니다.
