### ISSUE TITLE
파일 오류

### ISSUE THREAD

**Issue by bangduty** [ebandal/H2Orestart#18]
안녕하세요.
아래 첨부한 파일은 행정기관에서 수시로 배포하는 대외공개문서(400여 페이지)인데 열 수가 없습니다.
리눅스 데비안 12
리브르 오피스 7.4.
윈도우에서는 시도해 본 적이 없습니다.
다른 간단한 문서들은 잘 열립니다.
 
[files.zip](https://github.com/ebandal/H2Orestart/files/13911261/files.zip)

**Comment by ebandal** [comment]
안녕하세요. 
crash 원인은  문단 스타일 아이디 참조값이  음수로 읽히는 오류 때문이였습니다.
crash 외에도 개선할 부분이 보입니다만,  단시간에 해결하기 어려운 내용들이라 시간을 두고 차근히 개선해야 할것 같습니다.
쉽게 수정 가능한 부분 우선 적용하여  수일 내로 신규버전 배포하겠습니다.

**Comment by bangduty** [comment]
감사합니다.

**Comment by ebandal** [comment]
수정사항 반영하여 v0.5.10 배포합니다. 감사합니다.
