### ISSUE TITLE
표 안의 텍스트가 잘리는 현상

### ISSUE THREAD

**Issue by cyhbank** [ebandal/H2Orestart#24]
안녕하세요?
귀하의 오픈소스로 많은 도움을 받고 있는 사용자입니다.

한가지 궁금한 사항이 있어서 문의드립니다.

첨부된 파일을 보시면 아시겠지만 원본(hwp)의 표를 pdf로 변환해서 확인해보면
표 안의 텍스트가 잘려서 보이지 않는데, 해결책이 있을까요?

번창하시기를 기원합니다~

[표 샘플.zip](https://github.com/ebandal/H2Orestart/files/14329821/default.zip)

**Comment by ebandal** [comment]
안녕하세요. 
표의 테투리 속성 중 선의 너비를 변경하면 될것 같아 시도해보고 있는데,  잘 안되네요.  
좀더 시도해보고 알려드리겠습니다.

**Comment by cyhbank** [comment]
감사합니다~~

**Comment by cyhbank** [comment]
p{margin-top:0;margin-bottom:0}
    


    안녕하세요?이렇게 메일까지 주셔서 답변해주시고. 친절함에 감사드립니다.제가 올린 문의가 잘 해결되었으면 좋겠네요 ^^건강하시고 수고하세요~--------- 원본 메일 ---------

  
    보낸사람: ebandal ***@***.***>
    받는사람: ebandal/H2Orestart ***@***.***>
      참조: cyhbank ***@***.***>,Author ***@***.***>
    날짜: 24.02.20 00:19 GMT +0900
    
    제목: Re: [ebandal/H2Orestart] 표 안의 텍스트가 잘리는 현상 (Issue #24)
    
    
  
  
    
안녕하세요.
표의 테투리 속성 중 선의 너비를 변경하면 될것 같아 시도해보고 있는데,  잘 안되네요.
좀더 시도해보고 알려드리겠습니다.

**Comment by ebandal** [comment]
대략 이정도가 될것 같습니다.
[표 샘플_ToBe.pdf](https://github.com/ebandal/H2Orestart/files/14345350/_ToBe.pdf)
다음번 릴리스(v0.6.1) 에서  확인해주세요.   2월이내로 릴리스 계획입니다.

**Comment by cyhbank** [comment]
p{margin-top:0;margin-bottom:0}
    


    정말 고생 많으셨습니다~다음 릴리즈가 기다려집니다.항상 건강하시고 번창하시기를 바랍니다~수고하세요 ^^--------- 원본 메일 ---------

  
    보낸사람: ebandal ***@***.***>
    받는사람: ebandal/H2Orestart ***@***.***>
      참조: cyhbank ***@***.***>,Author ***@***.***>
    날짜: 24.02.20 22:56 GMT +0900
    
    제목: Re: [ebandal/H2Orestart] 표 안의 텍스트가 잘리는 현상 (Issue #24)
    
    
  
  
    
대략 이정도가 될것 같습니다.
표 샘플_ToBe.pdf
다음번 릴리스(v0.6.1) 에서  확인해주세요.   2월이내로 릴리스 계획입니다.

**Comment by ebandal** [comment]
v0.6.1 에서 개선되었습니다.  
이견이 없으시면 close 하겠습니다.
