### ISSUE TITLE
문서 일부의 하이라이트 표시

### ISSUE THREAD

**Issue by weird999** [ebandal/H2Orestart#31]
안녕하세요,

만들어주신 H2O restart를 너무나도 잘 사용하고 있습니다.

그런데 첨부 파일에서 문서 글 일부에 하이라이트(형광펜)가 한글에서는 안 보이는데 리브레 오피스에서는 보이고 있습니다.

한번 검토해주시면 감사 드리겠습니다. 

[서울특별시 상가 집합건물 표준관리규약 개정_2021.4.zip](https://github.com/ebandal/H2Orestart/files/14644202/_2021.4.zip)

**Comment by ebandal** [comment]
안녕하세요.  

이슈를 확인해보니,  확장에 오류가 있기도 했고,  미처 다루지 못했던 내용도 복합적으로 있음을 확인했습니다.
몇몇 부분에  글자모양에  형광펜 색깔로 "음영 색" 이 존재합니다만, 또한 글자모양 배경에는 흰색이 설정되어 있어서  한컴에서는 형광색이 나타나지 않음을 확인했습니다. 
본 확장에서는 글자모양 배경색상은 고려하고 있지 않았기에 음영색이 나타나게 된 것이고, 
한번 음영색이 나온 후로는 다음번 음영색 변경때까지  계속 나타나는 오류가 있음을 확인했습니다.
수정은 가능하여  다음 버전 릴리스시에 적용하겠습니다.

그 외에도  탭 표현이 잘 안되는 부분,  hwpx 에서 탭 표현이 아예 안되는 부분까지  개선하여 릴리스하겠습니다.

버그리포트 감사합니다.

**Comment by weird999** [comment]
H2O restart를 정말로 잘 사용하고 있어서 저야말로 감사드립니다.

큰 불편함이 없는 버그리포트이므로 천천히 여유있게 부탁드리겠습니다.

감사합니다.

**Comment by ebandal** [comment]
본건은 close하겠습니다.   추가 이슈가 있으면  새로운 issue report 생성해주세요.
