### ISSUE TITLE
ubuntu 패키지 설치 오류

### ISSUE THREAD

**Issue by koolerjaebee** [ebandal/H2Orestart#34]
윈도우 환경 WSL2 에서 ubuntu 22.04 (codename: jammy) 사용중입니다.

`sudo apt install libreoffice-h2orestart` 하면 결과가

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package libreoffice-h2orestart
이런 에러가 납니다.

패키지가 너무 최근 버전의 우분투만 지원하는 것 같은데 정확한 원인이 무엇일까요?
클라우드 환경에서 설치가 필요해서 libreoffice의 GUI는 최대한 지양하고 싶습니다.

**Comment by OctopusET** [comment]
https://packages.ubuntu.com/search?keywords=h2orestart

위 링크를 보시면 24.04 이후에 포함된것으로 나옵니다.

패키지를 통한 설치외에도 다음과 같은 방식으로 설치가 기능합니다.

압축을 풀어 올바른 위치에 옮기기:
https://wiki.documentfoundation.org/Documentation/HowTo/install_extension#Linux_bash_unzip_example

unopkg를 사용하기:
`unopkg add --shared {filename}.oxt`
https://manpages.ubuntu.com/manpages/bionic/man1/unopkg.1.html

**Comment by koolerjaebee** [comment]
감사합니다. oxt 파일을 통한 설치 참고하도록 하겠습니다.
