### ISSUE TITLE
이미지 크기 속성 값 불일치 오류

### ISSUE THREAD

**Issue by koolerjaebee** [ebandal/H2Orestart#35]
사용 환경: windows 11 WSL2 ubuntu 22.04 (codename: jammy)

원래 가지고 있던 이미지 속성 값 중 크기(size) 수치가 비정상적으로 작게 나옵니다.

original size로 바꾸면 원래대로 돌아가긴 하지만 이미 수정이 끝난 완성된 hwpx 파일을 pdf로 변환하려고 할 때 이미지가 제대로 표시되지 않아 사용에 문제가 있습니다. 테스트한 hwpx 파일 첨부드립니다.

[dummy.zip](https://github.com/ebandal/H2Orestart/files/15384893/dummy.zip)

**Comment by OctopusET** [comment]
사용하신 h2orestart 버전도 병기 해주시면 감사하겠습니다

**Comment by koolerjaebee** [comment]
H2Orestart 0.6.4 사용중입니다

**Comment by ebandal** [comment]
v0.6.2 버전에서  regression 이슈가 발생했네요.  이미지 cropping 처리가 들어가면서 오류가 있었나봅니다.
확인하고  다음번 릴리스에 개선하겠습니다.

**Comment by koolerjaebee** [comment]
H2Orestart 0.6.5 버전에서 문서상 이미지 정상 작동 확인했습니다. 감사합니다.
