### ISSUE TITLE
apple mac(m1/m2)에서 사용

### ISSUE THREAD

**Issue by itkairos2023** [ebandal/H2Orestart#37]
안녕하세요
애플 실리콘 맥에서 리브레오피스 사용 중입니다.

H2Orestart-0.6.5.oxt 가 jre8을 요구하여 jre-8u411-macosx-aarch64.dmg 를 설치 했습니다.

활성화 버튼 누르면 첨부의 오류가 발생하여 도움 요청드리고 싶습니다.

% java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.411-b09, mixed mode)

<img width="601" alt="ScreenShot 2024-06-26 22 53 05" src="https://github.com/ebandal/H2Orestart/assets/152257405/51d0bed2-c4be-4fd1-9900-bb4c3c320076">

**Comment by ebandal** [comment]
안녕하세요. 
제가 mac을 사용하지 않아서,  아래내용은 확인하고 알려드리는 것은 아닙니다. 

해당 경고창은 java를 인식하지 못해서 발생하는 것으로 보입니다. 
jre버전이 8 이상이기만 하면 되며,  꼭 jre8 일 필요는 없습니다.
확보하실 수 있는 apple silicon용 jre를 아무버전이나 설치하시면 됩니다. (17, 18, 21, ... 등)

jre 설치하신뒤  터미널을 여시고,  아래의 명령어로  java가 잘 인식되는지 확인합니다.
java -version 

리브레오피스 고급설정 창에서  Java Runtime Environment 를 인식하는지 확인합니다.  (아래처럼 생긴 고급설정 창을 찾아보세요.)
![image](https://github.com/ebandal/H2Orestart/assets/114871013/60e05d15-35d0-43f1-940c-96bfe6063580)
인식하지 못했다면,  Jre를 설치한 경로를 찾아서 추가합니다.


여기까지가 제가 드릴수 있는 가이드이고,  
이걸로 해결이 안된다면,  macOS에서 사용하고 계신 분들의 도움을 기다리셔야 할것 같습니다.

**Comment by itkairos2023** [comment]
안녕하세요 답변 감사합니다.
알려주신 내용이 큰 힌트가 되어 해결했습니다.
결론은 LibreOffice_7.6.7_MacOS_aarch64.dmg 설치하면 됩니다.
(기존에는 24.2.4 설치되어져 있었음)

https://ask.libreoffice.org/t/lo-7-2-5-2-on-macos-apple-silicon-no-longer-recognizes-a-jre-jdk/73298/9

**Comment by ebandal** [comment]
해결하신 걸로 이해하고 close 하겠습니다.
