### ISSUE TITLE
github clone시 폴더가 안보입니다. 

### ISSUE THREAD

**Issue by supersolaris** [ebandal/H2Orestart#4]
소스를 좀 보고 싶어서
clone https://github.com/ebandal/H2Orestart.git을 했는데 소스가 보이지 않습니다. 
저만 그런걸까요? 울트라 킹 왕초보라서 막막하기만 합니다.
한수 가르쳐 주심 너무 감사드리겠습니다.

**Comment by ebandal** [comment]
git clone 하면 아래의 화면처럼 소스가 받아집니다.
소스 받은 후에는  H2Orestart 폴더가 보일겁니다.
![image](https://github.com/ebandal/H2Orestart/assets/114871013/7e2f60da-864e-4a01-bd60-1ca154af0a01)

**Comment by ebandal** [comment]
@supersolaris 
git clone 시  나오는 메시지를 캡쳐해서 올려주시면,  더 의견을 드릴수 있겠습니다.
더이상 의견이 없으시면  close 할께요.
