### ISSUE TITLE
윈도우즈에서의 설치 실패

### ISSUE THREAD

**Issue by kjh0819** [ebandal/H2Orestart#40]
안녕하세요. 
윈도우즈에서 확장을 설치하다가 실패하였습니다.
사용한 버전은 0.6.6입니다.

OS: Windows11 home
Java Version: Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
LibreOffice Version: Version: 24.2.4.2 (X86_64) / LibreOffice Community

![image](https://github.com/ebandal/H2Orestart/assets/107752598/0b7ca0d0-6014-4ae1-b763-74f5f6300e45)

**Comment by ebandal** [comment]
안녕하세요. 

LibreOffice  [도구] - [기본 설정] - [고급 설정] 에서  Java Runtime Environment 설치화면 캡쳐해서 올려주시겠어요?
![image](https://github.com/ebandal/H2Orestart/assets/114871013/4420537f-67f2-43d6-9ad9-995fd96d678c)

**Comment by kjh0819** [comment]
![image](https://github.com/ebandal/H2Orestart/assets/107752598/cff9c43e-bd5e-4966-8466-12f988f0a5d6)
이 상태에서 오라클 JRE를 삭제 후 재설치 하여도 변화가 없고 JRE 경로를 수동으로 지정하여도 실패하였습니다.
그러나 MS OpenJDK 설치 후 문제가 해결되는 것으로 보아 확장 프로그램이 아닌 자바 혹은 리브레오피스의 오류였던 듯 합니다.
![image](https://github.com/ebandal/H2Orestart/assets/107752598/c299cbc5-0efd-415c-8f86-adb7eb73c93c)

이에 번거롭게 하여 죄송합니다.

**Comment by ebandal** [comment]
해결하셨다니 다행입니다.
close 하겠습니다.
