### ISSUE TITLE
[BUG] Cannot open hwpx file

### ISSUE THREAD

**Issue by OctopusET** [ebandal/H2Orestart#9]
I'm trying to open this hwpx document:
https://github.com/freedomofpress/dangerzone/raw/d8db4f0ec087c5efdd130dbe9716394c0940475a/tests/test_docs/sample-hwpx.hwpx

Libreoffice crashes with this message on the terminal ```terminate called after throwing an instance of 'com::sun::star::uno::RuntimeException'```

**Comment by OctopusET** [comment]
Test environment:
- H2ORestart: v0.5.5 and v0.5.6
- LibreOffice: 7.5.4
- JRE: OpenJDK 20.0.1.u9

**Comment by ebandal** [comment]
@OctopusET 
Thanks for reporting.
I found out that this file has TOTAL_PAGE of the numType attribute for autoNum node, that is the extension hasn't supported.
So I will add TOTAL_PAGE attribute in autoNum node. 
This fix will be included in v0.5.7.

**Comment by OctopusET** [comment]
https://github.com/ebandal/H2Orestart/releases/tag/v0.5.7

Released! Thank you so much
